leftnav:
- identifier: 980aca93-6605-b7b8-0bd6-2c012908683b
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 48ae9c48-8222-3fbb-d8f1-926f6f42f7f3
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: cdf6724b-9c26-859a-5829-cf2f18940552
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 1835271e-7f55-ae27-0928-64cea0d8d70a
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 40
- identifier: 7c4c1747-90b1-9c05-cdd9-4cd7c8d2573e
  name: Assignments
  url: /pages/assignments
  weight: 50
- identifier: 0f246db8-d617-428f-78ea-caf8540a1149
  name: Exams
  url: /pages/exams
  weight: 60
